### ISSUE TITLE
Kommentare Katharina

### ISSUE THREAD

**Issue by kmaibach** [jlab/teaching_V-BI-BSA#6]
Hi,

ich habe mir jetzt mal alles genau angeschaut und einige Kommentare gesammelt.
Im Großen sieht das echt toll aus und ich mag deine Erklärungen sehr. Ich denke, damit können die Studis sehr viel anfangen!

Hier dann mal meine Kommentare. Hoffentlich findest du die einzelnen Stellen gut wieder.
____________________________________________________________

`Installiere die folgenden Packages mit dem Befehl conda install PACKAGENAME:`

Vielleicht können wir das noch ändern: 
Conda ist unheimlich schlecht darin dependencies aufzulösen. Deswegen gibt es ein conda-package, welches das besser kann.
Heißt "mamba". Mamba muss man einmal via conda installieren und kann es dann zum Installieren von Paketen benutzen mit 
`mamba install PACKAGENAME`

Ist bei so vielen Studis und mehreren verschiedenen Paketen vielleicht sinnvoll.

Was dafür fehlt: `conda install -c conda-forge mamba`
Und dann statt `conda install ...` ein `mamba install ...` 
____________________________________________________________

`Wähle für dieses Jupyter-Notebook deinen neu erstellten Kernel "datenanalyse" aus`

Hier würde ich noch einen Punkt darüber machen, dass man ein neues Jupyter Notebook erstellen muss usw. (also: im richtigen Ordner erstellen, benennen und dann den Kernel auswählen)
____________________________________________________________

```
Um dir einen kurzen Überblick zu verschaffen, wie die Daten aussehn die wir verwenden, hier ein screenshot:

alt text
```

Ich kann den Screenshot hier leider nicht sehen. Ich weiß nicht, ob das anders ist wenn man sich das Notebook runterlädt.
____________________________________________________________

`Beim Einlesen der csv-Datei erhält man ein Object vom Typ DataFrame bestehend aus Reihen und Spalten. Die Überschriften der Spalten und Zeilen nennt man index`

Erst nennst du es "Reihen", dann "Zeilen". Würde einfach im 1. Satz zu "Zeilen" ändern, da du später auch immer "Zeilen" schreibst.
____________________________________________________________

`Für einen schnellen Überblick ist es immer praktisch sich nur die erten n Zeilen ausgeben zu lassen.`

Hier ist ein Typo drin: "die ersten n Zeilen" (ein s fehlt)
____________________________________________________________

Bei der Definition von `df1` und `df2` hast du `Organe` statt `Orange` stehen (Zelle 29)
____________________________________________________________

Bei 
```
test = df[Harnorgane&Frauen&Alter]
test.isin([112.4])
``` 
(Zelle 41) würde ich eine schönere Lösung wählen. So sieht man zwar, dass 2016 auf `true` steht, allerdings könnte auch in 2006-2009 `true` stehen - man sieht es nur nicht.

idxmax ist die perfekte Alternative, aber es wäre schön, wenn man das auch direkt sieht.
Bin mir aber nicht sicher, ob das so einfach machbar ist. Habe ein paar Sachen ausprobiert, aber die sind nicht so schön.
Vielleicht findest du ja was.
____________________________________________________________

`3.4 Plotten mit kategorialen Daten`

Hier würde ich vermutlich die einzelnen Parameter nicht einzeln zeigen sondern gemeinsam.
Also 1x den catplot ohne Parameter (wie du es direkt als erstes machst) und dann hinschreiben, dass es noch die Parameter hue und jitter gibt und sie doch ausprobieren sollen was sich verändert.
Dann einmal den Plot wo du hue und jitter zusammen einbaust.

Wichtig: hinschreiben, dass man bei `hue` hier keinen Effekt sieht, weil die Farben ja randomisiert zugeordnet wurden.

Box- und Violinplot finde ich gut, dass das einzeln steht - dazu fehlt halt noch ein bisschen Text. Gerade Boxplots sind ziemlich wichtig, dass das verstanden wird.
____________________________________________________________

Die Multiplots sind ziemlich cool.

Ansonsten habe ich noch ein paar Rechtschreibfehler gefunden, aber das würde ich dann ganz am Ende einmal kommentieren, wenn du einen pull request aufmachst. Dann kann ich direkt in den Zeilen kommentieren.

**Comment by miriKirsche** [comment]
Bis auf den Punkt mit mamba ist das issue bearbeitet. Falls das noch geändert werden soll, bitte einfach nochmal eine neues Issue auf machen.
